- apt: name={{item_pkg}}
  loop_control:
    loop_var: item_pkg
  with_items:
    - tmux
    - curl
    - tree
    - htop
    - mosh
    - vim
    - zsh
    - git
    - software-properties-common
    - jq
    - python-pip
  remote_user: root
  delegate_to: "{{current_host}}"
