---
  - include: facts.yml
  - file: dest={{remote_path}} state=directory
    remote_user: root
    delegate_to: "{{current_host}}"
  - set_fact: MONGO_URL="mongodb://mongodb/{{item.global_MONGO_URL_db_name}}"
  - set_fact: MONGO_OPTLOG_URL=MONGO_URL
  - template:
      dest: "{{remote_path}}docker-compose.yml"
      src: "docker-compose.yml"
    remote_user: root
    delegate_to: "{{current_host}}"
  - docker_service:
      project_src: "{{remote_path}}"
      state: present
      scale: 
        node: 4
    remote_user: root
    delegate_to: "{{current_host}}"
